# Generated by Django 2.0.2 on 2018-06-06 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20180605_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseuser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_user_set', to='registration.Course'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
