# Generated by Django 2.0.6 on 2018-08-08 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20180807_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examregistration',
            old_name='checkin_time_in',
            new_name='checkin_time',
        ),
        migrations.RenameField(
            model_name='examregistration',
            old_name='checkin_time_out',
            new_name='checkout_time',
        ),
        migrations.RenameField(
            model_name='historicalexamregistration',
            old_name='checkin_time_in',
            new_name='checkin_time',
        ),
        migrations.RenameField(
            model_name='historicalexamregistration',
            old_name='checkin_time_out',
            new_name='checkout_time',
        ),
        migrations.AddField(
            model_name='examregistration',
            name='checkout_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='registration.CourseUser'),
        ),
        migrations.AddField(
            model_name='historicalexamregistration',
            name='checkout_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registration.CourseUser'),
        ),
    ]
