# Generated by Django 2.0.6 on 2018-08-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_auto_20180808_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examslot',
            options={'ordering': ['exam', 'start_time_slot', 'exam_slot_type']},
        ),
    ]
