# Generated by Django 2.0.2 on 2018-05-26 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180525_0308'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('exam', 'start')},
        ),
    ]
