# Generated by Django 2.0.2 on 2018-05-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180526_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='America/New_York', help_text='Current time zone of the user.', max_length=32),
        ),
    ]
