# Generated by Django 2.0.2 on 2018-05-28 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_user_timezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['exam', 'start']},
        ),
        migrations.AddField(
            model_name='exam',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_registration_set', to='registration.TimeSlot'),
        ),
    ]
