# Generated by Django 2.0.2 on 2018-05-30 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20180528_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_slot_set', to='registration.Exam')),
            ],
            options={
                'ordering': ['exam', 'start_time_slot'],
            },
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['exam', 'start_time']},
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='start',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='time_slot',
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('exam', 'start_time')},
        ),
        migrations.AddField(
            model_name='examslot',
            name='start_time_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_slot', to='registration.TimeSlot'),
        ),
        migrations.AddField(
            model_name='examslot',
            name='time_slots',
            field=models.ManyToManyField(to='registration.TimeSlot'),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='exam_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_registration_set', to='registration.ExamSlot'),
        ),
    ]
