# Generated by Django 2.0.2 on 2018-05-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20180530_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examslot',
            name='time_slots',
            field=models.ManyToManyField(related_name='exam_slot_set', to='registration.TimeSlot'),
        ),
    ]
