# Generated by Django 2.0.2 on 2018-06-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20180530_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseuser',
            name='dropped',
            field=models.BooleanField(default=False),
        ),
    ]
