# Generated by Django 2.0.6 on 2018-06-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20180606_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseuser',
            options={'ordering': ('user__username',)},
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='dropped',
            field=models.BooleanField(default=False, help_text='Whether the student has dropped this course. This prevents the student from updating any information related to this course, although they can continue to log in.'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='lecture',
            field=models.CharField(blank=True, help_text="The student's lecture number", max_length=32),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='section',
            field=models.CharField(blank=True, help_text="The student's section number", max_length=32),
        ),
    ]
