# Generated by Django 2.0.6 on 2018-06-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_add_simple_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examregistration',
            options={'ordering': ['course_user__user__username']},
        ),
    ]
