# Generated by Django 2.0.6 on 2018-06-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20180628_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseuser',
            options={'ordering': ('user',)},
        ),
        migrations.AlterModelOptions(
            name='examregistration',
            options={'ordering': ('course_user',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',)},
        ),
    ]
