# Generated by Django 2.0.6 on 2018-06-28 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20180628_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examslot',
            name='start_time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_slot', to='registration.TimeSlot'),
        ),
    ]
