# Generated by Django 2.0.6 on 2018-08-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20180807_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='exam_password',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='historicalexamregistration',
            name='exam_password',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
