# Generated by Django 3.0.3 on 2020-02-26 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_githubtoken_historicalgithubtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['exam', 'start_time', 'room']},
        ),
        migrations.AddField(
            model_name='historicaltimeslot',
            name='room',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registration.Room'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slot_set', to='registration.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('exam', 'start_time', 'room')},
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='rooms',
        ),
    ]
