# Generated by Django 2.2.13 on 2020-06-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_auto_20200228_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubtoken',
            name='github_user_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='historicalgithubtoken',
            name='github_user_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
